// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

type EmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailSender) EXPECT() *EmailSender_Expecter {
	return &EmailSender_Expecter{mock: &_m.Mock}
}

// SendUploadSuccess provides a mock function with given fields: to
func (_m *EmailSender) SendUploadSuccess(to string) error {
	ret := _m.Called(to)

	if len(ret) == 0 {
		panic("no return value specified for SendUploadSuccess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EmailSender_SendUploadSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUploadSuccess'
type EmailSender_SendUploadSuccess_Call struct {
	*mock.Call
}

// SendUploadSuccess is a helper method to define mock.On call
//   - to string
func (_e *EmailSender_Expecter) SendUploadSuccess(to interface{}) *EmailSender_SendUploadSuccess_Call {
	return &EmailSender_SendUploadSuccess_Call{Call: _e.mock.On("SendUploadSuccess", to)}
}

func (_c *EmailSender_SendUploadSuccess_Call) Run(run func(to string)) *EmailSender_SendUploadSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *EmailSender_SendUploadSuccess_Call) Return(_a0 error) *EmailSender_SendUploadSuccess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EmailSender_SendUploadSuccess_Call) RunAndReturn(run func(string) error) *EmailSender_SendUploadSuccess_Call {
	_c.Call.Return(run)
	return _c
}

// NewEmailSender creates a new instance of EmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailSender {
	mock := &EmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
